Feature/justiceotuya/refactor landing page
team-helpme/helpme pull request #14
Opened 2019-05-14 23:04 UTC by justiceotuya

anding page refactor

2019-05-14 23:10 UTC, Way2nnadi commented on components/LandingPage/components/LandingPage.jsx
> +
destructure `landingPageContent`
```
landingPageContents.map(landingPageContent => {
    const { paragraphText, buttonIsPresent, ... } =  landingPageContent;
    return (< LandingPageContent ... />
}
```

2019-05-14 23:10 UTC, Way2nnadi commented on components/LandingPage/components/LandingPage.jsx
> +                    imageIsPresent={landingPageContent.imageIsPresent}
this should be in question format. so not `imageIsPresent` but rather `isImagePresent`

2019-05-14 23:11 UTC, Way2nnadi commented on components/LandingPage/components/LandingPage.jsx
> +                    buttonIsPresent={landingPageContent.buttonIsPresent}
question format

2019-05-14 23:12 UTC, Way2nnadi commented on components/LandingPage/constants.js
> +};
check this list of exports, which ones are you not using in other files?

2019-05-14 23:13 UTC, Way2nnadi commented on components/Layout/constants.jsx
> +import Link from 'next/link';
remove this two import from your constants.js file

2019-05-14 23:13 UTC, Way2nnadi commented on components/Layout/constants.jsx
> +);
if you are using this component in multiple places, make it its own component in its own file

2019-05-14 23:13 UTC, Way2nnadi requested changes
Minor changes, but this code is good to be merged down

2019-05-15 04:18 UTC, enyeInc commented on components/LandingPage/components/LandingPage.jsx
> +      landingPageContents.map(test => {
why are you call this parameter `test`?

2019-05-15 04:19 UTC, enyeInc commented on components/LandingPage/constants.js
> +};
check these exports, do export things that you are going to be using outside this file

2019-05-15 04:20 UTC, enyeInc commented on components/Layout/components/FooterListCreator.jsx
> +
component needs propTypes defined

2019-05-15 04:20 UTC, enyeInc commented on components/Layout/components/NavHeader.jsx
> +const { Search } = Input;
add new line here

2019-05-15 04:20 UTC, enyeInc commented on components/Layout/components/NavHeader.jsx
> +
remove unused line here

2019-05-15 04:21 UTC, enyeInc commented on components/Layout/components/PageFooter.jsx
> +
remove unused line

2019-05-15 04:21 UTC, enyeInc commented on components/Layout/components/PageLayout.jsx
> +
remove unused line

2019-05-15 04:21 UTC, enyeInc commented on components/Layout/components/Sidebar.jsx
> +
remove unused line

2019-05-15 04:21 UTC, enyeInc commented on components/Layout/components/Sidebar.jsx
> +                    sideBarMenuItems.map(sideBarItem => (
destructure `sideBarItem`

2019-05-15 04:22 UTC, enyeInc commented on components/Layout/components/FooterListCreator.jsx
> +                list.map(link => (
destructure `link`

2019-05-15 04:22 UTC, enyeInc commented on components/Layout/components/NavHeader.jsx
> +                                menuItems.map(menuItem => (
destructure menuitem

2019-05-15 06:06 UTC, enyeInc approved these changes
Looks good to me

2019-05-15 08:41 UTC, uimarshall commented on components/LandingPage/components/LandingPage.css
> -	margin-top: 64px;
Why not use 'rem' instead of 'px' for responsiveness

2019-05-15 09:10 UTC, justiceotuya commented on components/LandingPage/components/LandingPage.css
> -	margin-top: 64px;
this does not affect responsiveness, this just controls how high the content in the landing page is from the navbar. it is same for all mobile devices

2019-05-15 09:11 UTC, justiceotuya commented on components/LandingPage/components/LandingPage.css
> -	margin-top: 64px;
> Why not use 'rem' instead of 'px' for responsiveness

this does not affect responsiveness, this just controls how high the content in the landing page is from the navbar. it is same for all mobile devices

2019-05-15 09:14 UTC, uimarshall commented on components/LandingPage/components/LandingPage.css
> -	margin-top: 64px;
great

2019-05-15 09:14 UTC, merged