Feature/justiceotuya/signup
team-helpme/helpme pull request #17
Opened 2019-05-15 14:43 UTC by justiceotuya

finished the signup page

2019-05-15 15:37 UTC, EngrEric commented on components/Authentication/components/Login.jsx
> +    loginUsernameInputError,
constants should be upper case and separated with underscore. that is
`import {
    USERNAME_INPUT_ERROR,    PASSWORD_INPUT_ERROR
} from '../constants';`

2019-05-15 16:10 UTC, justiceotuya commented on components/Authentication/components/Login.jsx
> +    loginUsernameInputError,
done

2019-05-15 16:57 UTC, EngrEric commented on components/Authentication/components/Login.jsx
> +                        </Form.Item>
@justiceotuya  create a function that returns your `<Form.Item>...</Form.Item>` 
`function generateLoginForms(decorator) {`
   ` return INPUTS.map(input => {`
        `const { field, iconType, placeholder, rules, type } = input;`

       ` return (`
            `<FormItem`
              `  key={field}`
          `  >`
             `   {`
                `    decorator(field, {`
                 `       rules,`
                  `  })(`
                 `       <Input`
                          `  placeholder={placeholder}`
                        `    prefix={<Icon type={iconType} />}`
                       `     type={type}`
                     `   />`
               `     )`
             `   }`
         `   </FormItem>`
       ` );`
 `   });`
`}`

THE VALUE OF `INPUT` WILL LOOK LIKE
`INPUTS = [`
   ` {`
        `field: '',`
       ` iconType: "",`
      `  placeholder: "",`
       ` rules: [{ message: "", required: true }],`
  `  },`
  `  {`
    `    field: '',`
  `      iconType: "",`
  `      placeholder: "",`
   `     type: "",`
  `  },`
`];`

THEN YOUR `<form></form>` COMPONENT WILL LOOK LIKE
                `<Form>`
                   ` {generateLoginForms(getFieldDecorator)}`
                `</Form>`

2019-05-15 17:10 UTC, EngrEric commented on components/Authentication/components/SignUp.jsx
> +import {
all constants should be uppercase and separated with underscore as said above

2019-05-15 17:11 UTC, EngrEric commented on components/Authentication/components/SignUp.jsx
> +            callback('The Two passwords that you enter is inconsistent!');
move all strings to constants

2019-05-15 17:13 UTC, EngrEric commented on components/Authentication/components/SignUp.jsx
> +        console.log('dirty state', this.state.confirmDirty);
remove all `console.log()`
you want to use it when your PR is tagged WIP (work in progress).

2019-05-15 17:16 UTC, EngrEric commented on components/Authentication/components/SignUp.jsx
> +                                    validator: this.validateToNextPassword,
Do the same thing here as said in Loginform component

2019-05-15 17:17 UTC, EngrEric commented on components/Authentication/constants.js
> +    signupPasswordInputError,
all constants should be in uppercase

2019-05-15 17:18 UTC, EngrEric requested changes
looks good but needs some changes

2019-05-15 19:18 UTC, Way2nnadi submitted a review, later dismissed
Looks good to me

2019-05-15 19:22 UTC, enyeInc submitted a review, later dismissed

2019-05-17 19:29 UTC, enyeInc commented on components/Authentication/components/Login.jsx
> +    */
make sure you comments are indented properly

2019-05-17 19:30 UTC, enyeInc commented on components/Authentication/components/LoginInputItemGenerator.jsx
> +
needs component propType definition

2019-05-17 19:32 UTC, enyeInc commented on components/Authentication/components/SignUp.jsx
> +        isAgreementChecked: false,
so all booleans have to be in question format like `isAgreementChecked`.
```
isConfirmedDirty, isIconLoading, isLoading
```

2019-05-17 19:33 UTC, enyeInc submitted a review, later dismissed
Looking real good, some minor issues to fix but code is good to be merged down

2019-05-17 23:48 UTC, enyeInc commented on components/Authentication/components/SignUp.jsx
> +    */
fix doc indent

2019-05-22 07:09 UTC, enyeInc commented on components/Authentication/components/LoginInputItemGenerator.jsx
> +const LOGIN_INPUT_ITEM_GENERATOR = decorator => LOGIN_INPUTS.map(input => {
`LoginInputItemGenerator` is correct all caps and underscore separated for `constants` not components

2019-05-22 07:10 UTC, enyeInc commented on components/Authentication/components/SignUp.jsx
> +        console.log('dirty state', this.state.confirmDirty);
remove console.log on `line 70`

2019-05-22 07:10 UTC, enyeInc commented on components/Authentication/components/SignUp.jsx
> +            callback('The Two passwords that you enter is inconsistent!');
this is still pending

2019-05-22 07:11 UTC, enyeInc commented on components/Authentication/components/SignUp.jsx
> +*/
fix indent of esdocs

2019-05-22 07:11 UTC, enyeInc commented on components/Authentication/components/SignupInputItemGenerator.jsx
> +const SIGNUP_INPUT_GENERATOR = (actions, items, decorator) => {
this should be `SignUpInputGenerator`

2019-05-22 07:12 UTC, enyeInc submitted a review, later dismissed
Looks good to me, just need some minor clean up

2019-05-22 08:54 UTC, enyeInc submitted a review, later dismissed

2019-05-22 09:11 UTC, merged