Feature/daniel/profile model
team-helpme/helpme pull request #18
Opened 2019-05-17 13:11 UTC by cimthog

2019-05-18 17:44 UTC, enyeInc commented on server/controller/profile.contoller.js
> +    if (!req.body.city || !req.body.country || !req.body.email
destrcuture `req.body`
```
const { city, country ... } = req.body;
```

2019-05-18 17:44 UTC, enyeInc commented on server/controller/profile.contoller.js
> +exports.create = (req, res) => {
destrcuture `req.body`
```
const { city, country ... } = req.body;
```

2019-05-18 17:47 UTC, enyeInc commented on package.json
> -    "@babel/core": "^7.4.3",
dont you need `@babel/core` to be able to run `@babel/register`?

2019-05-18 17:48 UTC, enyeInc commented on server/index.js
> +
move the mongoose connect logic into its own file then import it here

2019-05-18 17:49 UTC, enyeInc commented on server/controller/profile.contoller.js
> +import Profile from '../models/profile.model';
go through this file and convert each function to leverage `async/await` pattern (https://javascript.info/async-await)

2019-05-18 17:51 UTC, enyeInc commented on package.json
> +    "@babel/register": "^7.4.4",
`@babel/register` is already in your dev dependencies. delete it from here

2019-05-18 18:31 UTC, uimarshall commented on server/controller/profile.contoller.js
> +import Profile from '../models/profile.model';
We already have a folder for models folder in the repo.No need to create another one. Your profile.model should go to this folder.

2019-05-18 18:31 UTC, uimarshall commented on server/controller/profile.contoller.js
> +
The controller folder and routes is more or less the same, use routes/api/profile.js to keep it simple.
The routes folder should be at the same level with the models folder, remove it from the server folder.

2019-05-22 10:53 UTC, cimthog commented on server/controller/profile.contoller.js
> +
done, please review

2019-05-22 10:54 UTC, cimthog commented on package.json
> +    "@babel/register": "^7.4.4",
removed

2019-05-22 10:54 UTC, cimthog commented on server/controller/profile.contoller.js
> +import Profile from '../models/profile.model';
done!

2019-05-22 10:56 UTC, justiceotuya requested changes
your package.json and server.js has a merge conflict. pull from master, solve the merge conflict and push back to this branch

2019-05-22 12:35 UTC, justiceotuya approved these changes

2019-05-22 13:16 UTC, uimarshall commented on models/profile.model.js
> +    image: {
Am curious about why you use contentType and buffer for image

2019-05-22 13:16 UTC, uimarshall commented on models/profile.model.js
> +    email: {
Will lowercase:true for email makes whatever the user type in to be lowercase? or it fails if the user put space or Capitalize?

2019-05-22 13:16 UTC, uimarshall commented on server/index.js
> -    app.use(bodyParser.urlencoded({ extended: true }));
Am curious about why you include this line: app.use(bodyParser.urlencoded({ extended: true }));

2019-05-22 19:50 UTC, enyeInc commented
@cimthog close this PR, create a new off master and add your changes to that branch. There is no reason why you should have over 900+ changes in this PR.

2019-05-22 21:19 UTC, closed without merging

2019-05-22 21:29 UTC, cimthog commented on models/profile.model.js
> +    email: {
it will save the email in lowercase

2019-05-22 21:43 UTC, cimthog commented on server/index.js
> -    app.use(bodyParser.urlencoded({ extended: true }));
testing on postman, i noticed that bodyparser.json() isn't working