Feature/justiceotuya/forgot password
team-helpme/helpme pull request #20
Opened 2019-05-22 11:36 UTC by justiceotuya

Added a forgot password component

2019-05-22 16:35 UTC, EngrEric commented on components/Authentication/components/PasswordReset.jsx
> +    * function that is used to close the message and redirect to the login page
comments on line 70 and 79 seems to be the same, are the two functions doing same thing?

2019-05-22 16:37 UTC, EngrEric requested changes
Looks good to me, do minor changes and remember to bump version

2019-05-22 19:59 UTC, enyeInc commented on components/Authentication/components/PasswordReset.jsx
> +                            <Button type="primary" htmlType="submit" loading={loading}>Request for Password Change</Button>
`Request for Password Change` string in `constants.js` file

2019-05-22 20:00 UTC, enyeInc submitted a review, later dismissed
Looks good to me

2019-05-22 20:26 UTC, justiceotuya commented on components/Authentication/components/PasswordReset.jsx
> +    * function that is used to close the message and redirect to the login page
done

2019-05-22 20:28 UTC, enyeInc commented on components/Authentication/components/PasswordReset.jsx
> +                                <Input prefix={<Icon type="user" style={{ color: 'rgba(0,0,0,.25)' }} />} />
no inline styles

2019-05-22 20:28 UTC, enyeInc commented on components/Authentication/components/PasswordReset.jsx
> +            message:
this can be on oneline

2019-05-22 20:36 UTC, justiceotuya commented on components/Authentication/components/PasswordReset.jsx
> +                                <Input prefix={<Icon type="user" style={{ color: 'rgba(0,0,0,.25)' }} />} />
done

2019-05-22 20:36 UTC, justiceotuya commented on components/Authentication/components/PasswordReset.jsx
> +            message:
done

2019-05-22 20:39 UTC, enyeInc approved these changes
LGTM

2019-05-23 06:48 UTC, olajohn-ajiboye approved these changes
All looks good. The only suggestion I have is to use absolute paths were possible instead of something like this "../../../static/forgot_password.svg". I will post a link to how to do this in the group.

2019-05-23 08:04 UTC, merged