Feature/marshall/login with passport auth0
team-helpme/helpme pull request #23
Opened 2019-05-24 14:39 UTC by uimarshall

For review

2019-05-24 22:37 UTC, justiceotuya requested changes
Please don't disable travis instead lets use it to write better code. forget about what other teams are doing. just fix its complaints and you will be fine

2019-05-24 22:37 UTC, justiceotuya commented on config/passport.js
> +        done(null, profile)
from the travis ci you got this message 

> Expected no linebreak before this expression  implicit-arrow-linebreak" 

Since you are returning just one line of code, it should be 

`(accessToken, refreshToken, extraParams, profile, done) => done(null, profile)`

2019-05-24 22:37 UTC, justiceotuya commented on lib/middleware/secure.js
> +};
from travis, you got this error 

> Expected to return a value at the end of async arrow function  consistent-return

so you need to return a value. what if it is not `req.user`, maybe @enyeInc can clarify as i dont really know much about the backend

2019-05-24 22:37 UTC, justiceotuya commented on routes/api/users.js
> +    passport.authenticate('auth0', (err, user) => {
Travis reported that 

> Expected to return a value at the end of arrow function  consistent-return

add a return statement here.  @enyeInc please verify

`return passport.authenticate('auth0', (err, user) => {}`

2019-05-24 22:37 UTC, justiceotuya commented on routes/api/users.js
> +        req.logIn(user, err => {
Travis reported that

> 'err' is already declared in the upper scope  

As i have said before, signup for travis so you can receive emails when your build fails or succed. it makes us write consistent code.

here is a link to show why your code failed [https://travis-ci.com/team-helpme/helpme/builds/113103244](url)

so it seems you have already declared error in the scope above. please find a fix

2019-05-24 22:37 UTC, justiceotuya commented on routes/api/users.js
> +            const { returnTo } = req.session;
**Travis Report:** Expected to return a value at the end of arrow function

add a return statement if it is not `err`

2019-05-24 22:37 UTC, justiceotuya commented on server/index.js
> +        saveUninitialized: true,
**Travis error:** Expected object keys to be in ascending order. 'saveUninitialized' should be before 'secret'

Your objects should be sorted alphabetically. so it should be

`const sess = { 
        cookie: {},
        resave: false,
        saveUninitialized: true,
        secret: 'CHANGE THIS TO A RANDOM SECRET',
}`

2019-05-25 19:30 UTC, Way2nnadi commented on config/passport.js
> +        domain: process.env.AUTH0_DOMAIN,
destructure `process.env`

2019-05-25 19:32 UTC, Way2nnadi commented on lib/middleware/secure.js
> +};
@justiceotuya you are right, it means that you should explicitly return a value from an arrow function if a `return` statement in found before the last line of code.

2019-05-25 19:32 UTC, Way2nnadi commented on routes/api/users.js
> +        client_id: process.env.AUTH0_CLIENT_ID,
destructure `process.env`

2019-05-25 19:33 UTC, Way2nnadi submitted a review, later dismissed
have some minors changes, but code looks good

2019-05-26 21:37 UTC, Way2nnadi submitted a review, later dismissed

2019-05-27 06:48 UTC, uimarshall commented on config/passport.js
> +        domain: process.env.AUTH0_DOMAIN,
Done!

2019-05-27 06:48 UTC, uimarshall commented on routes/api/users.js
> +        client_id: process.env.AUTH0_CLIENT_ID,
Done!

2019-05-28 16:09 UTC, enyeInc approved these changes
LGTM

2019-05-28 16:31 UTC, justiceotuya approved these changes

2019-05-28 16:31 UTC, merged