adds Post routes
team-helpme/helpme pull request #31
Opened 2019-06-01 14:05 UTC by uimarshall

For review

2019-06-01 17:51 UTC, enyeInc commented on routes/api/posts.js
> +// const mongoose = require("mongoose");
deleted unused code

2019-06-01 17:51 UTC, enyeInc commented on routes/api/posts.js
> +// Access: Not Protected route
i love this documentation, good job

2019-06-01 17:54 UTC, enyeInc commented on routes/api/posts.js
> +const express = require('express');
Go through these files and use `https://www.npmjs.com/package/http-status-codes` to replace your error code. then make sure that you are following the JSend Api when sending data back to the client (https://github.com/omniti-labs/jsend)

2019-06-01 17:56 UTC, enyeInc approved these changes
Code looks code, just make the convention changes and this is ready to be merged

2019-06-04 19:16 UTC, olajohn-ajiboye submitted a review, later dismissed

2019-06-04 19:53 UTC, enyeInc requested changes
@uimarshall this PR is still waiting for your changes

2019-06-06 23:30 UTC, Way2nnadi commented on routes/api/posts.js
> +            return res.status(BAD_REQUEST).json(errors);
`res.status(BAD_REQUEST).json({ errors });`

2019-06-06 23:31 UTC, Way2nnadi commented on routes/api/posts.js
> +            return res.status(BAD_REQUEST).json({ alreadyliked: 'User already liked this post' });
`res.status(BAD_REQUEST).json({ message: 'User already liked this post' });`

2019-06-06 23:31 UTC, Way2nnadi commented on routes/api/posts.js
> +            return res.status(BAD_REQUEST).json({ notliked: 'You need to like this post first!' });
`res.status(BAD_REQUEST).json({ message: 'You need to like this post first!' });`

2019-06-06 23:31 UTC, Way2nnadi commented on routes/api/posts.js
> +            return res.status(BAD_REQUEST).json(errors);
`res.status(BAD_REQUEST).json({ errors });

2019-06-06 23:31 UTC, Way2nnadi commented on routes/api/posts.js
> +            return res.status(BAD_REQUEST).json({ commentnotexists: 'Comment does not exist' });
`res.status(BAD_REQUEST).json({ message: 'Comment does not exist' });`

2019-06-07 01:05 UTC, Way2nnadi approved these changes

2019-06-07 09:02 UTC, justiceotuya approved these changes

2019-06-07 09:02 UTC, merged