Feature/justiceotuya/connecting redux
team-helpme/helpme pull request #33
Opened 2019-06-06 14:12 UTC by justiceotuya

2019-06-08 12:23 UTC, EngrEric commented on components/timeLine/reducers.js
>      case TOGGLE_MODAL:
I think controlling the modal will be better in the particular component you need it.
i.e setting an internal state instead. number of code will reduce and infinitesimal good performance will be achieved

2019-06-08 12:25 UTC, EngrEric commented on components/timeLine/components/TimeLine.jsx
> +                                // activeLikeButton={timelineData.like}
remove unused codes

2019-06-08 12:51 UTC, EngrEric reviewed
Looks good, just minor changes

2019-06-08 18:00 UTC, olajohn-ajiboye submitted a review, later dismissed

2019-06-08 18:25 UTC, Way2nnadi commented on components/timeLine/reducers.js
>      case TOGGLE_MODAL:
i would second that

2019-06-08 18:25 UTC, Way2nnadi commented on components/timeLine/index.js
> +import * as components from './components/index';
no need for `/index`, node imports from index by default

2019-06-08 18:27 UTC, Way2nnadi commented on components/timeLine/constants.js
> +export const data = (id, post) => ({
this is not a constant variable, this is a function. do not put it in the `constants.js` file. You can create a `utils` file if you need or define it in the function that uses this if it is not reuseable

2019-06-08 18:27 UTC, Way2nnadi commented on components/timeLine/components/TimeLine.jsx
> +                            //   textValue={commentValue}
@justiceotuya  clean up this file

2019-06-08 18:29 UTC, Way2nnadi commented on components/timeLine/components/TimeLine.css
> +    grid-row: 4;
keep css formatting consistent,
```
.ant-list-item-action {
    grid-row: 4;
}
```

2019-06-08 18:30 UTC, Way2nnadi commented on components/timeLine/actions.js
> +            post,
```
export const handlePostUpdate = payload => ({
    payload,
    type: ADD_POST_TO_TIMELINE,
};
```

2019-06-09 19:51 UTC, Way2nnadi commented on components/timeLine/actions.js
> +    UPDATE_STATUS, ADD_POST_TO_TIMELINE, TOGGLE_POST_LIKE, TOGGLE_POST_FAV, TOGGLE_COMMENT_BUTTON,
all on one line or each on there own line

2019-06-09 19:54 UTC, Way2nnadi commented on components/timeLine/actions.js
> +});
the pattern for each one of these action creators should be `payload` as the parameter.
```
export const commentButtonClicked = payload => ({
    payload,
    type: TOGGLE_COMMENT_BUTTON,
});
```
Make sure that when you call the action creator to pass it an object
```
...
commentButtonClicked({ id });
...
```

2019-06-09 19:54 UTC, Way2nnadi commented on components/timeLine/components/TimeLine.css
> +}
formatting is still not consistent on this page

2019-06-09 19:55 UTC, Way2nnadi commented on components/timeLine/components/TimeLine.jsx
> +export const data = (id, post) => ({
`const generateData`

2019-06-09 19:58 UTC, Way2nnadi commented on components/timeLine/reducers.js
> +        });
do not update the state object directly

2019-06-09 19:59 UTC, Way2nnadi commented on components/timeLine/reducers.js
> +        });
do not update the state object directly

2019-06-09 19:59 UTC, Way2nnadi commented on components/timeLine/reducers.js
> +        });
do not update the state object directly

2019-06-10 09:21 UTC, EngrEric commented on components/timeLine/components/TimeLine.jsx
> +} from '../actions';
if it cannot be contained in one line, each should be on a new line.
```
import {
    commentButtonClicked, 
    favButtonClicked, 
    fetchProfileData, 
    handlePostUpdate,
    likeButtonClicked, 
    setPostUpdateField
} from '../actions';
```

2019-06-10 09:28 UTC, EngrEric commented on components/timeLine/components/TimeLine.jsx
> +        if (isModalOpen) this.modalHandler();
```
if (isModalOpen) {
   this.modalHandler();
}
```
OR 
`isModalOpen && this.modalHandler()`

2019-06-10 09:42 UTC, EngrEric commented on components/timeLine/components/TimeLine.jsx
> +const mapDispatchToProps = dispatch => bindActionCreators({
`const mapDispatchToProps = dispatch => bindActionCreators(timeLineActions, dispatch);`

2019-06-10 10:19 UTC, EngrEric commented on components/timeLine/components/TimeLinePosts.jsx
> +                        {post.substr(0, 150)}
use `substring()` instead

2019-06-10 10:26 UTC, EngrEric commented on components/timeLine/reducers.js
>  export const reducers = (state = initialState, action) => {
this is more neat hence you aren't exporting any other thing here
`export default (state = initialState, action) => {`

2019-06-10 10:27 UTC, EngrEric commented on components/timeLine/reducers.js
> +        TOGGLE_POST_FAV, TOGGLE_COMMENT_BUTTON,
each should be in a new line

2019-06-10 10:28 UTC, EngrEric requested changes
Just need some minor changes

2019-06-10 14:20 UTC, Way2nnadi approved these changes
LGTM

2019-06-10 14:27 UTC, merged