Feature/justiceotuya/api connecting
team-helpme/helpme pull request #40
Opened 2019-06-14 21:24 UTC by justiceotuya

Sorry This is much but i coded all day and am still coding

2019-06-14 22:19 UTC, Way2nnadi commented on components/signup/components/SignupInputItemGenerator.jsx
> +* @param {string} label label for the input field
nit: `label` not `label label`

2019-06-14 22:23 UTC, Way2nnadi commented on components/signup/components/SignUp.jsx
> +    }).isRequired,
I love the attention to documentation here, both i don't think you need to document `form` given that it is an `AntD` component and has it own set of documentation

2019-06-14 22:24 UTC, Way2nnadi commented on components/signup/components/SignUp.jsx
> +    }).isRequired,
`form: PropTypes.object.isRequired`

2019-06-14 22:24 UTC, Way2nnadi commented on components/signup/components/SignupInputItemGenerator.jsx
> +    }
can you wrap this switch statement in a method or function or something. It doesn't feel right being here

2019-06-14 22:25 UTC, Way2nnadi commented on components/signup/sagas.js
> +    if (response.ok) {
you can't get the data is response is not ok

2019-06-14 22:26 UTC, Way2nnadi commented on components/signup/sagas.js
> +const REGISTRATION_URL = '/api/users/register';
move to `constants.js`

2019-06-14 22:26 UTC, Way2nnadi requested changes
Minor changes and potential error in saga

2019-06-14 22:29 UTC, justiceotuya commented on components/signup/components/SignUp.jsx
> +    }).isRequired,
Eslit does not allow PropTypes.object

2019-06-14 23:17 UTC, justiceotuya commented on components/signup/components/SignupInputItemGenerator.jsx
> +    }
I really dont know hoe to fix this. i have wrapped my heads and nothing seems to come out. this switch statement was the result of a complex function and i dont really know what to do

2019-06-15 09:21 UTC, Way2nnadi commented on components/signup/components/SignupInputItemGenerator.jsx
> +    }
okay leave it for now

2019-06-15 09:23 UTC, Way2nnadi commented on components/signup/components/SignUp.jsx
> +    }).isRequired,
that doesn't make any sense. `PropTypes.object` is valid (https://reactjs.org/docs/typechecking-with-proptypes.html)

2019-06-17 08:54 UTC, Way2nnadi approved these changes
LGTM

2019-06-17 09:03 UTC, merged