Feature/marshall/create user model
team-helpme/helpme pull request #9
Opened 2019-05-09 09:41 UTC by uimarshall

2019-05-16 06:11 UTC, olajohn-ajiboye reviewed
All looks good with this. I think it can be merged.

2019-05-16 06:14 UTC, olajohn-ajiboye requested changes
Remove all console.log()

2019-05-16 06:14 UTC, olajohn-ajiboye commented on test/connection.js
> +        .on('error', error => {
Remove console.logs()

2019-05-17 19:34 UTC, enyeInc approved these changes
LGTM

2019-05-17 20:06 UTC, merged